<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 6/30/17
 * Time: 11:26 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CombinacionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CombinacionItemRepository extends EntityRepository
{

}