<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 6/19/16
 * Time: 10:37 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenRepository extends EntityRepository
{

}