<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 5/7/16
 * Time: 11:12 p.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MonedaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonedaRepository extends EntityRepository
{

}