<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 6/9/17
 * Time: 12:39 a.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrdenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenRepository extends EntityRepository
{
    private $doctrineManager;

    public function setDoctrineManager($_doctrineManager)
    {
        $this->doctrineManager = $_doctrineManager;
    }

    public function obtenerSinTerminarDesde($fecha)
    {
        $resultset = $this->getEntityManager()
            ->createQuery(
                "SELECT o FROM AppBundle:Orden o
             JOIN o.estado e
             WHERE e.id >= 1 AND e.id <= 8 AND o.fechaentrega >= :fecha
             ORDER BY o.fechaentrega")
            ->setParameter("fecha", $fecha)
            ->getResult();

        return $resultset;
    }

    public function obtenerSinTerminarAnterioresA($fecha)
    {
        $resultset = $this->getEntityManager()
            ->createQuery(
                "SELECT o FROM AppBundle:Orden o
             JOIN o.estado e
             WHERE e.id >= 1 AND e.id <= 8 AND o.fechaentrega < :fecha
             ORDER BY o.fechaentrega")
            ->setParameter("fecha", $fecha)
            ->getResult();

        return $resultset;
    }

    public function obtenerFacturadasTerminadas()
    {
        $resultset = $this->getEntityManager()
            ->createQuery(
                "SELECT o FROM AppBundle:Orden o
             JOIN o.estado e
             WHERE (e.id = 9 OR e.id = 10 OR e.id = 11) AND o.especial=0
             ORDER BY o.id DESC")
            ->getResult();

        return $resultset;
    }

    public function obtenerFacturadasEspeciales()
    {
        $resultset = $this->getEntityManager()
            ->createQuery(
                "SELECT o FROM AppBundle:Orden o
             JOIN o.estado e
             WHERE (e.id = 9 OR e.id = 10 OR e.id = 11) AND o.especial=1
             ORDER BY o.id DESC")
            ->getResult();

        return $resultset;
    }







// -------


    public function obtenerSinFacturar()
    {
        $resultset = $this->getEntityManager()
            ->createQuery(
                "SELECT o FROM AppBundle:Orden o
             JOIN o.estado e
             WHERE e.id >= 1 AND e.id <= 9")
            ->getResult();

        return $resultset;
    }

    public function obtenerConFactura()
    {
        $resultset = $this->getEntityManager()
            ->createQuery(
                "SELECT o FROM AppBundle:Orden o
             JOIN o.estado e
             WHERE e.id = 10 OR e.id = 11")
            ->getResult();

        return $resultset;
    }

}