<?php
/**
 * Created by PhpStorm.
 * User: davatar
 * Date: 6/9/17
 * Time: 12:39 a.m.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    public function productoEnUso($producto)
    {
        $connection = $this->getEntityManager()->getConnection();

        // 1. Productos en uso
        $statement = $connection->prepare("SELECT COUNT(*) as c FROM ventaitem WHERE id_producto=:idProducto");
        $statement->bindValue("idProducto", $producto->getId());
        $statement->execute();
        $resultado = $statement->fetchAll();

        $count = $resultado[0][c];

        // 2. Productos en uso
        $statement = $connection->prepare("SELECT COUNT(*) as c FROM ventaitempaqueteproducto WHERE id_producto=:idProducto");
        $statement->bindValue("idProducto", $producto->getId());
        $statement->execute();
        $resultado = $statement->fetchAll();

        $count = $count + $resultado[0][c];

        if ($count>0)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
}