<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Venta extends \AppBundle\Entity\Venta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('items' => NULL, 'itempaquetes' => NULL, 'digitos' => NULL, 'idcotizacion' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->items, $this->itempaquetes, $this->digitos, $this->idcotizacion);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'vendedor', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'sucursal', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'seccion', 'items', 'itempaquetes', 'subtotal', 'iva', 'total', 'propina', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'moneda', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'ticket', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'mediopago', 'digitos', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'fecharecepcion', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'cortecaja', 'idcotizacion', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'token', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'facturada');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'vendedor', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'sucursal', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'seccion', 'subtotal', 'iva', 'total', 'propina', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'moneda', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'ticket', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'mediopago', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'fecharecepcion', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'cortecaja', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'token', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'activo', '' . "\0" . 'AppBundle\\Entity\\Venta' . "\0" . 'facturada');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Venta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->items, $this->itempaquetes, $this->digitos, $this->idcotizacion);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal($subtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal', array($subtotal));

        return parent::setSubtotal($subtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal', array());

        return parent::getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva($iva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva', array($iva));

        return parent::setIva($iva);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva', array());

        return parent::getIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa(\AppBundle\Entity\Empresa $empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setSucursal(\AppBundle\Entity\Sucursal $sucursal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSucursal', array($sucursal));

        return parent::setSucursal($sucursal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSucursal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSucursal', array());

        return parent::getSucursal();
    }

    /**
     * {@inheritDoc}
     */
    public function addItem(\AppBundle\Entity\VentaItem $items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItem', array($items));

        return parent::addItem($items);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItem(\AppBundle\Entity\VentaItem $items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItem', array($items));

        return parent::removeItem($items);
    }

    /**
     * {@inheritDoc}
     */
    public function getItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', array());

        return parent::getItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneda(\AppBundle\Entity\Moneda $moneda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneda', array($moneda));

        return parent::setMoneda($moneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneda', array());

        return parent::getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicket($ticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicket', array($ticket));

        return parent::setTicket($ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicket', array());

        return parent::getTicket();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacturada($facturada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacturada', array($facturada));

        return parent::setFacturada($facturada);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacturada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacturada', array());

        return parent::getFacturada();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropina($propina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropina', array($propina));

        return parent::setPropina($propina);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropina', array());

        return parent::getPropina();
    }

    /**
     * {@inheritDoc}
     */
    public function addItempaquete(\AppBundle\Entity\VentaItemPaquete $itempaquetes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItempaquete', array($itempaquetes));

        return parent::addItempaquete($itempaquetes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItempaquete(\AppBundle\Entity\VentaItemPaquete $itempaquetes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItempaquete', array($itempaquetes));

        return parent::removeItempaquete($itempaquetes);
    }

    /**
     * {@inheritDoc}
     */
    public function getItempaquetes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItempaquetes', array());

        return parent::getItempaquetes();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeccion(\AppBundle\Entity\Seccion $seccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeccion', array($seccion));

        return parent::setSeccion($seccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeccion', array());

        return parent::getSeccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMediopago(\AppBundle\Entity\MedioPago $mediopago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMediopago', array($mediopago));

        return parent::setMediopago($mediopago);
    }

    /**
     * {@inheritDoc}
     */
    public function getMediopago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMediopago', array());

        return parent::getMediopago();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\AppBundle\Entity\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setVendedor(\AppBundle\Entity\Usuario $vendedor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVendedor', array($vendedor));

        return parent::setVendedor($vendedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendedor', array());

        return parent::getVendedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCortecaja(\AppBundle\Entity\CorteCaja $cortecaja = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCortecaja', array($cortecaja));

        return parent::setCortecaja($cortecaja);
    }

    /**
     * {@inheritDoc}
     */
    public function getCortecaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCortecaja', array());

        return parent::getCortecaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecharecepcion($fecharecepcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecharecepcion', array($fecharecepcion));

        return parent::setFecharecepcion($fecharecepcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecharecepcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecharecepcion', array());

        return parent::getFecharecepcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcotizacion($idcotizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcotizacion', array($idcotizacion));

        return parent::setIdcotizacion($idcotizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcotizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcotizacion', array());

        return parent::getIdcotizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', array($token));

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', array());

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setDigitos($digitos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDigitos', array($digitos));

        return parent::setDigitos($digitos);
    }

    /**
     * {@inheritDoc}
     */
    public function getDigitos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDigitos', array());

        return parent::getDigitos();
    }

}
