<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CorteCaja extends \AppBundle\Entity\CorteCaja implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('numventasefectivo' => NULL, 'numventastarjetacredito' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->numventasefectivo, $this->numventastarjetacredito);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'resultado', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'sucursal', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'fechainicio', 'fechainiciostr', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'fechafin', 'fechafinstr', 'totalefectivo', 'totaltarjetacredito', 'totalefectivoreportado', 'totaltarjetacreditoreportado', 'remanente', 'propinasefectivo', 'propinastarjetacredito', 'numventasefectivo', 'numventastarjetacredito', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'moneda', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'activo');
        }

        return array('__isInitialized__', 'id', 'resultado', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'sucursal', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'fechainicio', 'fechainiciostr', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'fechafin', 'fechafinstr', 'totalefectivo', 'totaltarjetacredito', 'totalefectivoreportado', 'totaltarjetacreditoreportado', 'remanente', 'propinasefectivo', 'propinastarjetacredito', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'moneda', '' . "\0" . 'AppBundle\\Entity\\CorteCaja' . "\0" . 'activo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CorteCaja $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->numventasefectivo, $this->numventastarjetacredito);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalefectivo($totalefectivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalefectivo', array($totalefectivo));

        return parent::setTotalefectivo($totalefectivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalefectivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalefectivo', array());

        return parent::getTotalefectivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotaltarjetacredito($totaltarjetacredito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotaltarjetacredito', array($totaltarjetacredito));

        return parent::setTotaltarjetacredito($totaltarjetacredito);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotaltarjetacredito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotaltarjetacredito', array());

        return parent::getTotaltarjetacredito();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalefectivoreportado($totalefectivoreportado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalefectivoreportado', array($totalefectivoreportado));

        return parent::setTotalefectivoreportado($totalefectivoreportado);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalefectivoreportado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalefectivoreportado', array());

        return parent::getTotalefectivoreportado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotaltarjetacreditoreportado($totaltarjetacreditoreportado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotaltarjetacreditoreportado', array($totaltarjetacreditoreportado));

        return parent::setTotaltarjetacreditoreportado($totaltarjetacreditoreportado);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotaltarjetacreditoreportado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotaltarjetacreditoreportado', array());

        return parent::getTotaltarjetacreditoreportado();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemanente($remanente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemanente', array($remanente));

        return parent::setRemanente($remanente);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemanente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemanente', array());

        return parent::getRemanente();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa(\AppBundle\Entity\Empresa $empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setSucursal(\AppBundle\Entity\Sucursal $sucursal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSucursal', array($sucursal));

        return parent::setSucursal($sucursal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSucursal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSucursal', array());

        return parent::getSucursal();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\AppBundle\Entity\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneda(\AppBundle\Entity\Moneda $moneda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneda', array($moneda));

        return parent::setMoneda($moneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneda', array());

        return parent::getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumventasefectivo($numventasefectivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumventasefectivo', array($numventasefectivo));

        return parent::setNumventasefectivo($numventasefectivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumventasefectivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumventasefectivo', array());

        return parent::getNumventasefectivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumventastarjetacredito($numventastarjetacredito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumventastarjetacredito', array($numventastarjetacredito));

        return parent::setNumventastarjetacredito($numventastarjetacredito);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumventastarjetacredito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumventastarjetacredito', array());

        return parent::getNumventastarjetacredito();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicio($fechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicio', array($fechainicio));

        return parent::setFechainicio($fechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicio', array());

        return parent::getFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechafin($fechafin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechafin', array($fechafin));

        return parent::setFechafin($fechafin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechafin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechafin', array());

        return parent::getFechafin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainiciostr($fechainiciostr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainiciostr', array($fechainiciostr));

        return parent::setFechainiciostr($fechainiciostr);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainiciostr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainiciostr', array());

        return parent::getFechainiciostr();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechafinstr($fechafinstr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechafinstr', array($fechafinstr));

        return parent::setFechafinstr($fechafinstr);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechafinstr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechafinstr', array());

        return parent::getFechafinstr();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropinasefectivo($propinasefectivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropinasefectivo', array($propinasefectivo));

        return parent::setPropinasefectivo($propinasefectivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropinasefectivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropinasefectivo', array());

        return parent::getPropinasefectivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropinastarjetacredito($propinastarjetacredito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropinastarjetacredito', array($propinastarjetacredito));

        return parent::setPropinastarjetacredito($propinastarjetacredito);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropinastarjetacredito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropinastarjetacredito', array());

        return parent::getPropinastarjetacredito();
    }

}
