<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Orden extends \AppBundle\Entity\Orden implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('items' => NULL, 'pagos' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->items, $this->pagos);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'maquina', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'foliofactura', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'cotizacion', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'sucursal', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'seccion', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'cliente', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'contacto', 'subtotal', 'iva', 'total', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'moneda', 'items', 'itemsaux', 'itemsauxactualizados', 'itemsauxborrados', 'pagos', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'motivocancelacion', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'fechaentrega', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'fecharecepcion', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'block', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'medidaimpresion', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'papel', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'folio', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'impresionopciones', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'colorinicial', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'colorcfb', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'colorcf', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'especial', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'usocfdi', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'metodopago', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'mediopago', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'activo', 'abono');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'maquina', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'foliofactura', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'cotizacion', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'sucursal', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'seccion', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'cliente', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'contacto', 'subtotal', 'iva', 'total', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'moneda', 'itemsaux', 'itemsauxactualizados', 'itemsauxborrados', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'motivocancelacion', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'fechaentrega', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'fecharecepcion', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'block', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'medidaimpresion', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'papel', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'folio', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'impresionopciones', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'colorinicial', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'colorcfb', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'colorcf', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'especial', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'usocfdi', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'metodopago', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'mediopago', '' . "\0" . 'AppBundle\\Entity\\Orden' . "\0" . 'activo', 'abono');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Orden $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->items, $this->pagos);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecharecepcion($fecharecepcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecharecepcion', array($fecharecepcion));

        return parent::setFecharecepcion($fecharecepcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecharecepcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecharecepcion', array());

        return parent::getFecharecepcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\AppBundle\Entity\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa(\AppBundle\Entity\Empresa $empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setSucursal(\AppBundle\Entity\Sucursal $sucursal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSucursal', array($sucursal));

        return parent::setSucursal($sucursal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSucursal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSucursal', array());

        return parent::getSucursal();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeccion(\AppBundle\Entity\Seccion $seccion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeccion', array($seccion));

        return parent::setSeccion($seccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeccion', array());

        return parent::getSeccion();
    }

    /**
     * {@inheritDoc}
     */
    public function addItem(\AppBundle\Entity\OrdenItem $items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItem', array($items));

        return parent::addItem($items);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItem(\AppBundle\Entity\OrdenItem $items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItem', array($items));

        return parent::removeItem($items);
    }

    /**
     * {@inheritDoc}
     */
    public function getItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', array());

        return parent::getItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setItems($items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItems', array($items));

        return parent::setItems($items);
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(\AppBundle\Entity\OrdenEstado $estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivocancelacion($motivocancelacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivocancelacion', array($motivocancelacion));

        return parent::setMotivocancelacion($motivocancelacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivocancelacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivocancelacion', array());

        return parent::getMotivocancelacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal($subtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal', array($subtotal));

        return parent::setSubtotal($subtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal', array());

        return parent::getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva($iva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva', array($iva));

        return parent::setIva($iva);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva', array());

        return parent::getIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaentrega($fechaentrega)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaentrega', array($fechaentrega));

        return parent::setFechaentrega($fechaentrega);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaentrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaentrega', array());

        return parent::getFechaentrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\AppBundle\Entity\Cliente $cliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', array($cliente));

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setContacto(\AppBundle\Entity\Contacto $contacto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContacto', array($contacto));

        return parent::setContacto($contacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacto', array());

        return parent::getContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemsaux($itemsaux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemsaux', array($itemsaux));

        return parent::setItemsaux($itemsaux);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsaux()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsaux', array());

        return parent::getItemsaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemsauxactualizados($itemsauxactualizados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemsauxactualizados', array($itemsauxactualizados));

        return parent::setItemsauxactualizados($itemsauxactualizados);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsauxactualizados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsauxactualizados', array());

        return parent::getItemsauxactualizados();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemsauxborrados($itemsauxborrados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemsauxborrados', array($itemsauxborrados));

        return parent::setItemsauxborrados($itemsauxborrados);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsauxborrados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsauxborrados', array());

        return parent::getItemsauxborrados();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneda(\AppBundle\Entity\Moneda $moneda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneda', array($moneda));

        return parent::setMoneda($moneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneda', array());

        return parent::getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function actualizarTotales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'actualizarTotales', array());

        return parent::actualizarTotales();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlock($block)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlock', array($block));

        return parent::setBlock($block);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlock', array());

        return parent::getBlock();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedidaimpresion($medidaimpresion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedidaimpresion', array($medidaimpresion));

        return parent::setMedidaimpresion($medidaimpresion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedidaimpresion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedidaimpresion', array());

        return parent::getMedidaimpresion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPapel($papel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPapel', array($papel));

        return parent::setPapel($papel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPapel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPapel', array());

        return parent::getPapel();
    }

    /**
     * {@inheritDoc}
     */
    public function addImpresionopcione(\AppBundle\Entity\ImpresionOpcion $impresionopciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImpresionopcione', array($impresionopciones));

        return parent::addImpresionopcione($impresionopciones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImpresionopcione(\AppBundle\Entity\ImpresionOpcion $impresionopciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImpresionopcione', array($impresionopciones));

        return parent::removeImpresionopcione($impresionopciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpresionopciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpresionopciones', array());

        return parent::getImpresionopciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setCotizacion(\AppBundle\Entity\Cotizacion $cotizacion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCotizacion', array($cotizacion));

        return parent::setCotizacion($cotizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCotizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCotizacion', array());

        return parent::getCotizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoliofactura($foliofactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoliofactura', array($foliofactura));

        return parent::setFoliofactura($foliofactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoliofactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoliofactura', array());

        return parent::getFoliofactura();
    }

    /**
     * {@inheritDoc}
     */
    public function getSaldopagado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaldopagado', array());

        return parent::getSaldopagado();
    }

    /**
     * {@inheritDoc}
     */
    public function getSaldopendiente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaldopendiente', array());

        return parent::getSaldopendiente();
    }

    /**
     * {@inheritDoc}
     */
    public function getSaldopagadoregistrado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaldopagadoregistrado', array());

        return parent::getSaldopagadoregistrado();
    }

    /**
     * {@inheritDoc}
     */
    public function addPago(\AppBundle\Entity\Pago $pagos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPago', array($pagos));

        return parent::addPago($pagos);
    }

    /**
     * {@inheritDoc}
     */
    public function removePago(\AppBundle\Entity\Pago $pagos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePago', array($pagos));

        return parent::removePago($pagos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagos', array());

        return parent::getPagos();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagos($pagos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagos', array($pagos));

        return parent::setPagos($pagos);
    }

    /**
     * {@inheritDoc}
     */
    public function setEspecial($especial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspecial', array($especial));

        return parent::setEspecial($especial);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspecial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspecial', array());

        return parent::getEspecial();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsocfdi(\AppBundle\Entity\UsoCFDI $usocfdi = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsocfdi', array($usocfdi));

        return parent::setUsocfdi($usocfdi);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsocfdi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsocfdi', array());

        return parent::getUsocfdi();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetodopago(\AppBundle\Entity\MetodoPago $metodopago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetodopago', array($metodopago));

        return parent::setMetodopago($metodopago);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetodopago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetodopago', array());

        return parent::getMetodopago();
    }

    /**
     * {@inheritDoc}
     */
    public function setMediopago(\AppBundle\Entity\MedioPago $mediopago = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMediopago', array($mediopago));

        return parent::setMediopago($mediopago);
    }

    /**
     * {@inheritDoc}
     */
    public function getMediopago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMediopago', array());

        return parent::getMediopago();
    }

    /**
     * {@inheritDoc}
     */
    public function setFolio($folio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFolio', array($folio));

        return parent::setFolio($folio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFolio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFolio', array());

        return parent::getFolio();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(\AppBundle\Entity\OrdenTipo $tipo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaquina(\AppBundle\Entity\Maquina $maquina = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaquina', array($maquina));

        return parent::setMaquina($maquina);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaquina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaquina', array());

        return parent::getMaquina();
    }

    /**
     * {@inheritDoc}
     */
    public function setColorcfb($colorcfb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColorcfb', array($colorcfb));

        return parent::setColorcfb($colorcfb);
    }

    /**
     * {@inheritDoc}
     */
    public function getColorcfb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColorcfb', array());

        return parent::getColorcfb();
    }

    /**
     * {@inheritDoc}
     */
    public function setColorcf($colorcf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColorcf', array($colorcf));

        return parent::setColorcf($colorcf);
    }

    /**
     * {@inheritDoc}
     */
    public function getColorcf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColorcf', array());

        return parent::getColorcf();
    }

    /**
     * {@inheritDoc}
     */
    public function setColorinicial($colorinicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColorinicial', array($colorinicial));

        return parent::setColorinicial($colorinicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getColorinicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColorinicial', array());

        return parent::getColorinicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbono($abono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbono', array($abono));

        return parent::setAbono($abono);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbono', array());

        return parent::getAbono();
    }

}
