<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \AppBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('sucursales' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->sucursales);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'username', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'empresa', 'sucursales', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'roles', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'token', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'fechaExpiracionToken', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'imagen', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'firma', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'firmaimagen', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'isActive');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'username', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'roles', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'token', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'fechaExpiracionToken', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'imagen', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'firma', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'firmaimagen', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'isActive');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->sucursales);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole(\AppBundle\Entity\Rol $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', array($roles));

        return parent::addRole($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole(\AppBundle\Entity\Rol $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', array($roles));

        return parent::removeRole($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', array($token));

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', array());

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaExpiracionToken($fechaExpiracionToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaExpiracionToken', array($fechaExpiracionToken));

        return parent::setFechaExpiracionToken($fechaExpiracionToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaExpiracionToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaExpiracionToken', array());

        return parent::getFechaExpiracionToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function addSeguidor(\AppBundle\Entity\Usuario $seguidores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSeguidor', array($seguidores));

        return parent::addSeguidor($seguidores);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSeguidor(\AppBundle\Entity\Usuario $seguidores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSeguidor', array($seguidores));

        return parent::removeSeguidor($seguidores);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeguidores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeguidores', array());

        return parent::getSeguidores();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', array($isActive));

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', array());

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen(\AppBundle\Entity\Imagen $imagen = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', array($imagen));

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', array());

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa(\AppBundle\Entity\Empresa $empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', array($apellidos));

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', array());

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function addSucursale(\AppBundle\Entity\Sucursal $sucursales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSucursale', array($sucursales));

        return parent::addSucursale($sucursales);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSucursale(\AppBundle\Entity\Sucursal $sucursales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSucursale', array($sucursales));

        return parent::removeSucursale($sucursales);
    }

    /**
     * {@inheritDoc}
     */
    public function getSucursales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSucursales', array());

        return parent::getSucursales();
    }

    /**
     * {@inheritDoc}
     */
    public function addRoles2(\AppBundle\Entity\Rol $rol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRoles2', array($rol));

        return parent::addRoles2($rol);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRoles2(\AppBundle\Entity\Sucursal $rol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRoles2', array($rol));

        return parent::removeRoles2($rol);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles2', array());

        return parent::getRoles2();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirma(\AppBundle\Entity\Imagen $firma = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirma', array($firma));

        return parent::setFirma($firma);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirma', array());

        return parent::getFirma();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombrecompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombrecompleto', array());

        return parent::getNombrecompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirmaimagen($firmaimagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirmaimagen', array($firmaimagen));

        return parent::setFirmaimagen($firmaimagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirmaimagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirmaimagen', array());

        return parent::getFirmaimagen();
    }

}
