<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cotizacion extends \AppBundle\Entity\Cotizacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('items' => NULL, 'itempaquetes' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->items, $this->itempaquetes);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'sucursal', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'seccion', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'cliente', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'contacto', 'subtotal', 'iva', 'total', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'moneda', 'items', 'itemsaux', 'itemsauxactualizados', 'itemsauxborrados', 'itempaquetes', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'motivocancelacion', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'fechavalida', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'fecharecepcion', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'tiempoentrega', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'esquemapago', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'activo');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'empresa', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'sucursal', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'seccion', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'cliente', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'contacto', 'subtotal', 'iva', 'total', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'moneda', 'itemsaux', 'itemsauxactualizados', 'itemsauxborrados', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'motivocancelacion', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'fechavalida', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'fecharecepcion', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'tiempoentrega', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'esquemapago', '' . "\0" . 'AppBundle\\Entity\\Cotizacion' . "\0" . 'activo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cotizacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->items, $this->itempaquetes);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecharecepcion($fecharecepcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecharecepcion', array($fecharecepcion));

        return parent::setFecharecepcion($fecharecepcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecharecepcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecharecepcion', array());

        return parent::getFecharecepcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', array($activo));

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', array());

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\AppBundle\Entity\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa(\AppBundle\Entity\Empresa $empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', array($empresa));

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', array());

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setSucursal(\AppBundle\Entity\Sucursal $sucursal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSucursal', array($sucursal));

        return parent::setSucursal($sucursal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSucursal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSucursal', array());

        return parent::getSucursal();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeccion(\AppBundle\Entity\Seccion $seccion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeccion', array($seccion));

        return parent::setSeccion($seccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeccion', array());

        return parent::getSeccion();
    }

    /**
     * {@inheritDoc}
     */
    public function addItem(\AppBundle\Entity\CotizacionItem $items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItem', array($items));

        return parent::addItem($items);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItem(\AppBundle\Entity\CotizacionItem $items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItem', array($items));

        return parent::removeItem($items);
    }

    /**
     * {@inheritDoc}
     */
    public function getItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', array());

        return parent::getItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addItempaquete(\AppBundle\Entity\CotizacionItemPaquete $itempaquetes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItempaquete', array($itempaquetes));

        return parent::addItempaquete($itempaquetes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItempaquete(\AppBundle\Entity\CotizacionItemPaquete $itempaquetes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItempaquete', array($itempaquetes));

        return parent::removeItempaquete($itempaquetes);
    }

    /**
     * {@inheritDoc}
     */
    public function getItempaquetes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItempaquetes', array());

        return parent::getItempaquetes();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(\AppBundle\Entity\CotizacionEstado $estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivocancelacion($motivocancelacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivocancelacion', array($motivocancelacion));

        return parent::setMotivocancelacion($motivocancelacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivocancelacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivocancelacion', array());

        return parent::getMotivocancelacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal($subtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal', array($subtotal));

        return parent::setSubtotal($subtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal', array());

        return parent::getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva($iva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva', array($iva));

        return parent::setIva($iva);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva', array());

        return parent::getIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechavalida($fechavalida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavalida', array($fechavalida));

        return parent::setFechavalida($fechavalida);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavalida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavalida', array());

        return parent::getFechavalida();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\AppBundle\Entity\Cliente $cliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', array($cliente));

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setContacto(\AppBundle\Entity\Contacto $contacto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContacto', array($contacto));

        return parent::setContacto($contacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacto', array());

        return parent::getContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemsaux($itemsaux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemsaux', array($itemsaux));

        return parent::setItemsaux($itemsaux);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsaux()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsaux', array());

        return parent::getItemsaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemsauxactualizados($itemsauxactualizados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemsauxactualizados', array($itemsauxactualizados));

        return parent::setItemsauxactualizados($itemsauxactualizados);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsauxactualizados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsauxactualizados', array());

        return parent::getItemsauxactualizados();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemsauxborrados($itemsauxborrados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemsauxborrados', array($itemsauxborrados));

        return parent::setItemsauxborrados($itemsauxborrados);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsauxborrados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsauxborrados', array());

        return parent::getItemsauxborrados();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneda(\AppBundle\Entity\Moneda $moneda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneda', array($moneda));

        return parent::setMoneda($moneda);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneda', array());

        return parent::getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function actualizarTotales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'actualizarTotales', array());

        return parent::actualizarTotales();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiempoentrega($tiempoentrega)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiempoentrega', array($tiempoentrega));

        return parent::setTiempoentrega($tiempoentrega);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiempoentrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiempoentrega', array());

        return parent::getTiempoentrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsquemapago(\AppBundle\Entity\EsquemaPago $esquemapago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsquemapago', array($esquemapago));

        return parent::setEsquemapago($esquemapago);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsquemapago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsquemapago', array());

        return parent::getEsquemapago();
    }

}
